# Generated by Django 5.0.6 on 2024-07-16 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_auctioneer_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auctioneer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
