# Generated by Django 5.0.6 on 2024-07-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bids',
            name='title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
