# Generated by Django 5.0.6 on 2024-07-29 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bids_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='title',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
