# Generated by Django 5.0.6 on 2024-08-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comments_comment_comments_listing_comments_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
