# Generated by Django 5.0.6 on 2024-08-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_comments_username_comments_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='listing',
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
