# Generated by Django 5.0.6 on 2024-08-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_comments_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='title',
            new_name='listing',
        ),
    ]
