# Generated by Django 5.0.6 on 2024-08-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
