# Generated by Django 5.0.6 on 2024-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.TextField(blank=True),
        ),
    ]
